sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tKpjYx8s3fRQM2461Bj
    access-key-secret: vm5w3dtPwQ2Wp2NMirY29hdtpfOAuY
    bucket-name: sky-take-out-imge
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx49a7b54edcf44f38
    secret: 37e9f1e8bff1f8156414d255f5d6b8fe